### PR TITLE
Fix bug with many watchers

### LINKED ISSUE #70: Add test with multiple watchers in combination with the Qt scheduler

### PR DESCRIPTION
**Pull request by berendkleinhaneveld**
Closes #70.

There is a bug in the traverse code that is triggered when using many watchers (on the same data?). It seems that the traverse code skips objects that have been 'seen' before, but apparently this does not seem to work how we thought it would work...

Instead, when we simply traverse everything, then all the watchers are properly queued and triggered.

### CODE REVIEW

**Comment by Korijn** [comment]
Well, first of all, this opens up the possibility of an infinite recursion cycle, no?

```py
a = {}
b = {}
a["b"] = b
b["a"] = a
```

And, other than that, I don't understand why this fixes the problem. It's not like the different objects contained in the state can have the same id, right?

**Comment by berendkleinhaneveld** [comment]
Let me start by saying that I am probably as confused as you are. I also know that infinite recursion would be a problem, but I guess we could try and solve that in some other way (like how we count cycles in `scheduler.flush`)?

I am just not sure that we understand `id()` well enough in this context. It might also have to do something with the recursive nature of the `watcher.get` function.

Btw: if you want to investigate yourself, you can change the number from 100 to 3 in the test (and revert the changes to `traverse`, you should be able to reliably trigger the problem. The weird thing is that the number of watchers that do get called is not stable: it fluctuates between 0 and 2 (when you change the amount of watchers to 3). This is what confuses me the most :/

**Comment by Korijn** [comment]
I'll give it a try right now.

**Comment by Korijn** [comment]
> Let me start by saying that I am probably as confused as you are. I also know that infinite recursion would be a problem, but I guess we could try and solve that in some other way (like how we count cycles in `scheduler.flush`)?

The scheduler.flush method is feasible because it can index watchers by id. I thought about just tracking the recursion depth, but that wouldn't provide any advantage over the recursion error Python would already trigger on its own.

That's when I realized, we're not doing this just to detect cycles, we're doing this to actually _support_ traversal (and thereby watching) of datastructures with cycles.

> I am just not sure that we understand `id()` well enough in this context. It might also have to do something with the recursive nature of the `watcher.get` function.

Well, there is a gotcha with `id()`, from the docs: "Two objects with non-overlapping lifetimes may have the same `id()` value." So we _must_ be falling into that trap here. From that I am going to guess that our proxies are being garbage collected and recreated. This makes sense to me and explains your observations!

---

Anyway: I think I have fixed the problem by reintroducing `seen`, but with a list.

I'm wondering if it would be safer to unwrap proxies during traversal (grabbing `proxy.target`).

**Comment by Korijn** [comment]
> Let me start by saying that I am probably as confused as you are. I also know that infinite recursion would be a problem, but I guess we could try and solve that in some other way (like how we count cycles in `scheduler.flush`)?

The scheduler.flush method is feasible because it can index watchers by id. I thought about just tracking the recursion depth, but that wouldn't provide any advantage over the recursion error Python would already trigger on its own.

That's when I realized, we're not doing this just to detect cycles, we're doing this to actually _support_ traversal (and thereby watching) of datastructures with cycles.

> I am just not sure that we understand `id()` well enough in this context. It might also have to do something with the recursive nature of the `watcher.get` function.

Well, there is a gotcha with `id()`, from the docs: "Two objects with non-overlapping lifetimes may have the same `id()` value." So we _must_ be falling into that trap here. From that I am going to guess that our proxies are being garbage collected and recreated. This makes sense to me and explains your observations!

---

Anyway: I think I have fixed the problem by reintroducing `seen`, but with a list.

**Comment by Korijn** [comment]
> I'm wondering if it would be safer to unwrap proxies during traversal (grabbing `proxy.target`).

I'm pretty sure it is, by the logic above. Added that, tests still seem to pass!

**Comment by Korijn** [comment]
I was fooling myself, forgot to pass seen down the recursion. Still works though, thankfully :) Also tried to test with much larger (10k) and much smaller (3) amounts of watchers.

**Comment by Korijn** [comment]
Ah, I just realized, unwrapping is not needed. By tracking proxies in the seen list, they cannot be garbage collected during traversal! You can go ahead and merge this now :)

**Comment by berendkleinhaneveld** [comment]
> Well, there is a gotcha with `id()`, from the docs: "Two objects with non-overlapping lifetimes may have the same `id()` value." So we _must_ be falling into that trap here. From that I am going to guess that our proxies are being garbage collected and recreated. This makes sense to me and explains your observations!

Aha! That's good to know!

Good idea to track the objects themselves instead of their ids.

**Pull request merged**
