### PR TITLE
Add simple benchmark

### LINKED ISSUE #38: Benchmarks
Would be nice to have a benchmark setup so that we can make informed decisions on performance.

We could leverage pytest-benchmark together with [github-action-benchmark](https://github.com/benchmark-action/github-action-benchmark).
And naturally we would need to have some proper functions to run as benchmark.

### PR DESCRIPTION
**Pull request by Korijn**
Closes #38

Mostly just trying out pytest-benchmark.

### CODE REVIEW

**Comment by berendkleinhaneveld** [comment]
Cool! Nice idea to compare against plain objects. Do you want to add the other types as well? (lists and sets)

**Comment by Korijn** [comment]
> Cool! Nice idea to compare against plain objects. Do you want to add the other types as well? (lists and sets)

Yeah right now it's just adding keys to a dict. I have been thinking about what would be interesting _comparisons_.

I am imagining a benchmark matrix for the following axes:

* Mode: plain, proxy, shallow
* Type: lists, sets and dicts
* Trap: read, iterate, read_key, write, write_key, delete, delete_key

I don't think the readonly functionality would make sense here.

Other than that there's code we can simply benchmark (without comparison) to measure when we improve/worsen performance.

* to_raw
* ProxyDb
  * In particular ProxyDb.cleanup is probably a prime candidate to micro-optimize

Not sure yet how to approach watchers, the store and the scheduler.

**Comment by Korijn** [comment]
I decided to keep it simple for now and get this into a state where we can merge it.

Example output:

```console
❯ poetry run pytest bench
====================================================================== test session starts =======================================================================
platform win32 -- Python 3.9.9, pytest-7.4.2, pluggy-1.3.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
PySide6 6.6.0 -- Qt runtime 6.6.0 -- Qt compiled 6.6.0
rootdir: C:\Users\kvang\dev\observ
configfile: pyproject.toml
plugins: benchmark-4.0.0, cov-4.1.0, qt-4.2.0, timeout-2.2.0, xvfb-3.0.0
timeout: 3.0s
timeout method: thread
timeout func_only: False
collected 6 items

bench\test_bench.py ......                                                                                                                                  [100%]


-------------------- benchmark 'dict_plain_vs_reactive': 2 tests ---------------------
Name (time in ms)                             Mean            StdDev            Rounds
--------------------------------------------------------------------------------------
test_dict_plain_vs_reactive[plain]          2.9616 (1.0)      0.3461 (1.0)         366
test_dict_plain_vs_reactive[reactive]     340.3825 (114.93)   8.1101 (23.43)         5
--------------------------------------------------------------------------------------

-------------------- benchmark 'list_plain_vs_reactive': 2 tests ---------------------
Name (time in ms)                             Mean            StdDev            Rounds
--------------------------------------------------------------------------------------
test_list_plain_vs_reactive[plain]          2.1133 (1.0)      0.0883 (1.0)         427
test_list_plain_vs_reactive[reactive]     202.2988 (95.73)    0.6289 (7.12)          5
--------------------------------------------------------------------------------------

--------------------- benchmark 'set_plain_vs_reactive': 2 tests --------------------
Name (time in ms)                            Mean            StdDev            Rounds
-------------------------------------------------------------------------------------
test_set_plain_vs_reactive[plain]          5.1571 (1.0)      0.1878 (1.0)         193
test_set_plain_vs_reactive[reactive]     173.6121 (33.66)    1.2938 (6.89)          6
-------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
======================================================================= 6 passed in 9.31s ========================================================================
```

**Comment by Korijn** [comment]
With commit 683d213 I managed to make observ 2x faster :)

line_profiler was very helpful in hunting down the causes!

```console
❯ poetry run pytest bench
=================================================================================================================== test session starts ===================================================================================================================
platform win32 -- Python 3.9.9, pytest-7.4.2, pluggy-1.3.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
PySide6 6.6.0 -- Qt runtime 6.6.0 -- Qt compiled 6.6.0
rootdir: C:\Users\kvang\dev\observ
configfile: pyproject.toml
plugins: benchmark-4.0.0, cov-4.1.0, qt-4.2.0, timeout-2.2.0, xvfb-3.0.0
timeout: 3.0s
timeout method: thread
timeout func_only: False
collected 6 items

bench\test_bench.py ......                                                                                                                                                                                                                           [100%]


-------------------- benchmark 'dict_plain_vs_reactive': 2 tests ---------------------
Name (time in ms)                             Mean            StdDev            Rounds
--------------------------------------------------------------------------------------
test_dict_plain_vs_reactive[plain]          2.8660 (1.0)      0.1432 (1.0)         380
test_dict_plain_vs_reactive[reactive]     130.6601 (45.59)    3.5672 (24.91)         8
--------------------------------------------------------------------------------------

-------------------- benchmark 'list_plain_vs_reactive': 2 tests ---------------------
Name (time in ms)                             Mean            StdDev            Rounds
--------------------------------------------------------------------------------------
test_list_plain_vs_reactive[plain]          1.9972 (1.0)      0.1354 (1.0)         487
test_list_plain_vs_reactive[reactive]     103.5774 (51.86)    2.5528 (18.85)        11
--------------------------------------------------------------------------------------

--------------------- benchmark 'set_plain_vs_reactive': 2 tests --------------------
Name (time in ms)                            Mean            StdDev            Rounds
-------------------------------------------------------------------------------------
test_set_plain_vs_reactive[plain]          4.9565 (1.0)      0.1447 (1.0)         204
test_set_plain_vs_reactive[reactive]     114.4079 (23.08)    3.3890 (23.42)         9
-------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
==================================================================================================================== 6 passed in 8.21s ====================================================================================================================
```

**Pull request merged**
